// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOs6f2xaWkbFzPr4_5J_ainp61_k-1vfE',
    appId: '1:321735824503:web:d8a72c9c67c85a39e42272',
    messagingSenderId: '321735824503',
    projectId: 'whatmeal-101',
    authDomain: 'whatmeal-101.firebaseapp.com',
    storageBucket: 'whatmeal-101.firebasestorage.app',
    measurementId: 'G-6H2TGDSHW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzK9iApy520TZ4LZ1M0FEQd_WDpgsYJhA',
    appId: '1:321735824503:android:9a4bf975671f2b46e42272',
    messagingSenderId: '321735824503',
    projectId: 'whatmeal-101',
    storageBucket: 'whatmeal-101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ1yB-55Cnqz67ZTo3mx8pf-fiOJ27jS0',
    appId: '1:321735824503:ios:ccf8cb4894e26dade42272',
    messagingSenderId: '321735824503',
    projectId: 'whatmeal-101',
    storageBucket: 'whatmeal-101.firebasestorage.app',
    iosBundleId: 'com.example.whatmeal',
  );
}
