import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';

import 'package:provider/provider.dart';
import 'app.dart';
import 'firebase_options.dart';
import 'features/meal_plan/data/meal_plan_repository.dart';
import 'core/services/user_service.dart';
import 'core/services/family_service.dart';
import 'core/services/llm_service.dart';
import 'core/services/firestore_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options generated by FlutterFire CLI.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    // Firebase AI Logic requires App Check on every generate call.
    // DEBUG providers only. Before a real release build, switch to:
    //   androidProvider: AndroidProvider.playIntegrity
    //   appleProvider: AppleProvider.appAttest
    //   webProvider: ReCaptchaV3Provider('<real reCAPTCHA v3 site key>')
    await FirebaseAppCheck.instance.activate(
      webProvider: ReCaptchaV3Provider('debug'),
      androidProvider: AndroidProvider.debug,
      appleProvider: AppleProvider.debug,
    );
    try {
      final token = await FirebaseAppCheck.instance.getToken(true);
      debugPrint('[APP-CHECK-DEBUG-TOKEN] $token');
    } catch (e) {
      debugPrint('[APP-CHECK-DEBUG-TOKEN] failed to fetch token: $e');
    }
    final firestoreService = FirestoreService();
    await firestoreService.enablePersistence();
  } catch (e) {
    debugPrint('Firebase initialization notice: $e');
  }

  runApp(
    MultiProvider(
      providers: [
        Provider(create: (_) => UserService()),
        Provider(create: (_) => FamilyService()),
        Provider(create: (_) => LlmService()),
        Provider(create: (_) => FirestoreService()),
        ChangeNotifierProvider(create: (_) => MealPlanRepository()),
      ],
      child: const WhatMealApp(),
    ),
  );
}
